Use xsltproc to transform ctest error output.

diff --git a/scripts/ci/extends/template-build-linux.yml b/scripts/ci/extends/template-build-linux.yml
--- a/scripts/ci/extends/template-build-linux.yml
+++ b/scripts/ci/extends/template-build-linux.yml
@@ -22,7 +22,17 @@
       if [[ -z "$TARGETS" ]]; then
           $BUILD_CMD_PREFIX cmake --build . --target package > >(tee make.output)
           if [ "$BUILD_TESTS" = true ] ; then $BUILD_CMD_PREFIX cmake --build . --target tests ; fi
-          if [ "$BUILD_CTEST" = true ] ; then $BUILD_CMD_PREFIX cmake --build . --target ctest ; fi
+
+          if [ "$BUILD_CTEST" = true ]; then
+            ctest_exit=0
+            ctest -T Test --no-compress-output --exclude-regex LARGE --timeout 900 || ctest_exit=$?
+            if [ $ctest_exit -ne 0 ]; then
+              echo "ctests failed (showing the last ${NUM_CTEST_ERROR_LINES} lines):"
+              xsltproc ${CI_PROJECT_DIR}/scripts/test/ctest-error-output.xsl Testing/*/Test.xml | tail -n ${NUM_CTEST_ERROR_LINES}
+              exit $ctest_exit
+            fi
+          fi
+
           if [ "$BUILD_CTEST_LARGE" = true ] ; then $BUILD_CMD_PREFIX cmake --build . --target ctest-large ; fi
           if [ "$BUILD_CTEST" = true ] ; then cp Testing/**/Test.xml Tests/ctest.xml ; fi
           if [ "$BUILD_CTEST_LARGE" = true ] ; then cp Testing/**/Test.xml Tests/ctest-large.xml ; fi
