[ci] invalid project files must fail `ogs-inspect:all-tests` job

diff --git a/scripts/ci/jobs/ogs-inspect.yml b/scripts/ci/jobs/ogs-inspect.yml
--- a/scripts/ci/jobs/ogs-inspect.yml
+++ b/scripts/ci/jobs/ogs-inspect.yml
@@ -41,4 +41,15 @@ ogs-inspect:all-tests:
   rules:
     - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
   script:
-    - find Tests/Data -type f -name '*.prj' -print0 | xargs -0 -r ./ogs-inspect lint --fail-on-warnings
+    # All valid project files must pass
+    - find Tests/Data -path '*/InvalidProjectFiles' -prune -o -type f -name '*.prj' -print0 | xargs -0 -r ./ogs-inspect lint --fail-on-warnings
+
+    # All invalid project files must fail
+    - |
+      find Tests/Data -type f -name '*.prj' -path '*/InvalidProjectFiles/*' -print0 |
+        xargs -0 -r -P"$(nproc)" -n1 sh -c '
+          if ./ogs-inspect lint --quiet --fail-on-warnings "$1"; then
+            echo "Expected lint failure: $1"
+            exit 1
+          fi
+        ' sh
